// WordDrop word bank — edit freely, no game-code changes needed.
// Each entry: word, part of speech, and a sentence with ~ where the word sits.
window.WORDDROP_POS = ["NOUN", "ADVERB", "VERB", "ADJECTIVE", "PREPOSITION", "PRONOUN"];

window.WORDDROP_WORDS = [
  { w: "MARKET", pos: "NOUN", s: "The ~ was busy long before sunrise." },
  { w: "SILENCE", pos: "NOUN", s: "A long ~ followed her question." },
  { w: "HARBOUR", pos: "NOUN", s: "Three boats left the ~ at dawn." },
  { w: "THEORY", pos: "NOUN", s: "His ~ turned out to be wrong." },
  { w: "CANDLE", pos: "NOUN", s: "She lit a ~ and closed the door." },
  { w: "JOURNEY", pos: "NOUN", s: "The ~ took them eleven days." },
  { w: "TEACHER", pos: "NOUN", s: "Our ~ handed back the essays." },
  { w: "BRIDGE", pos: "NOUN", s: "The old ~ shook in the wind." },
  { w: "ANSWER", pos: "NOUN", s: "Nobody knew the ~ to that one." },
  { w: "WINTER", pos: "NOUN", s: "That ~ was the coldest on record." },
  { w: "PUZZLE", pos: "NOUN", s: "The ~ had one piece missing." },
  { w: "MIRROR", pos: "NOUN", s: "A cracked ~ hung in the hall." },
  { w: "VILLAGE", pos: "NOUN", s: "The whole ~ came to watch." },

  { w: "COLLAPSED", pos: "VERB", s: "The plan ~ within a week." },
  { w: "SETTLE", pos: "VERB", s: "Let the dust ~ before you decide." },
  { w: "WHISPER", pos: "VERB", s: "He would only ~ the news." },
  { w: "GATHER", pos: "VERB", s: "They ~ by the gate each morning." },
  { w: "REFUSED", pos: "VERB", s: "She ~ the offer twice." },
  { w: "CLIMB", pos: "VERB", s: "We ~ the ridge before noon." },
  { w: "DELIVER", pos: "VERB", s: "They ~ the parcels by bike." },
  { w: "VANISHED", pos: "VERB", s: "The keys simply ~ overnight." },
  { w: "REPAIR", pos: "VERB", s: "He can ~ almost any engine." },
  { w: "INVENT", pos: "VERB", s: "You cannot ~ an excuse that good." },
  { w: "ARRIVED", pos: "VERB", s: "The letter ~ a month late." },
  { w: "BORROW", pos: "VERB", s: "May I ~ your notes tonight?" },

  { w: "RELUCTANT", pos: "ADJECTIVE", s: "He gave a ~ nod and picked up his bag." },
  { w: "BRIEF", pos: "ADJECTIVE", s: "There was a ~ pause on the line." },
  { w: "FRAGILE", pos: "ADJECTIVE", s: "The box held something ~." },
  { w: "HONEST", pos: "ADJECTIVE", s: "It was an ~ mistake." },
  { w: "CROWDED", pos: "ADJECTIVE", s: "The platform was ~ by seven." },
  { w: "ANCIENT", pos: "ADJECTIVE", s: "An ~ oak stood in the yard." },
  { w: "CLEVER", pos: "ADJECTIVE", s: "That was a ~ way to fix it." },
  { w: "BITTER", pos: "ADJECTIVE", s: "The tea had a ~ taste." },
  { w: "NARROW", pos: "ADJECTIVE", s: "They took the ~ path home." },
  { w: "SUDDEN", pos: "ADJECTIVE", s: "A ~ storm cleared the beach." },
  { w: "GENEROUS", pos: "ADJECTIVE", s: "It was a ~ offer, all the same." },
  { w: "SILENT", pos: "ADJECTIVE", s: "The house stayed ~ all evening." },

  { w: "SWIFTLY", pos: "ADVERB", s: "The news travelled ~ through the school." },
  { w: "RARELY", pos: "ADVERB", s: "She ~ speaks in meetings." },
  { w: "LOUDLY", pos: "ADVERB", s: "He laughed ~ at his own joke." },
  { w: "ALMOST", pos: "ADVERB", s: "We ~ missed the last train." },
  { w: "GENTLY", pos: "ADVERB", s: "Close the lid ~." },
  { w: "OFTEN", pos: "ADVERB", s: "They ~ walk the long way back." },
  { w: "CAREFULLY", pos: "ADVERB", s: "He folded the map ~." },
  { w: "SOON", pos: "ADVERB", s: "The rain will stop ~." },
  { w: "BADLY", pos: "ADVERB", s: "The team played ~ in the first half." },
  { w: "QUIETLY", pos: "ADVERB", s: "She left the room ~." },
  { w: "ALWAYS", pos: "ADVERB", s: "He ~ forgets his umbrella." },
  { w: "EAGERLY", pos: "ADVERB", s: "They waited ~ for the results." },

  { w: "BENEATH", pos: "PREPOSITION", s: "The cat slept ~ the stairs." },
  { w: "DURING", pos: "PREPOSITION", s: "He woke twice ~ the night." },
  { w: "TOWARD", pos: "PREPOSITION", s: "She walked ~ the far gate." },
  { w: "BETWEEN", pos: "PREPOSITION", s: "The letter fell ~ two books." },
  { w: "AGAINST", pos: "PREPOSITION", s: "The ladder leaned ~ the wall." },
  { w: "BESIDE", pos: "PREPOSITION", s: "A lamp stood ~ the door." },
  { w: "WITHOUT", pos: "PREPOSITION", s: "They left ~ their coats." },
  { w: "THROUGH", pos: "PREPOSITION", s: "Light poured ~ the high window." },
  { w: "ACROSS", pos: "PREPOSITION", s: "We rowed ~ the lake at dusk." },
  { w: "BEYOND", pos: "PREPOSITION", s: "The track ran ~ the last house." },
  { w: "AMONG", pos: "PREPOSITION", s: "One coin lay ~ the pebbles." },
  { w: "UNTIL", pos: "PREPOSITION", s: "Nothing moved ~ the bell rang." },

  { w: "THEY", pos: "PRONOUN", s: "By six ~ had finished the roof." },
  { w: "OURS", pos: "PRONOUN", s: "The blue tent is ~." },
  { w: "HERSELF", pos: "PRONOUN", s: "She painted the shed ~." },
  { w: "NOBODY", pos: "PRONOUN", s: "~ answered the second knock." },
  { w: "THEM", pos: "PRONOUN", s: "The guide waved ~ through." },
  { w: "MINE", pos: "PRONOUN", s: "That coat on the hook is ~." },
  { w: "EVERYONE", pos: "PRONOUN", s: "~ agreed to start again." },
  { w: "ITSELF", pos: "PRONOUN", s: "The door swung shut by ~." },
  { w: "SOMEONE", pos: "PRONOUN", s: "~ had left the light on." },
  { w: "YOURS", pos: "PRONOUN", s: "The last slice is ~." },
  { w: "WHOEVER", pos: "PRONOUN", s: "~ finishes first can leave." },
  { w: "ANYONE", pos: "PRONOUN", s: "Did ~ see the fox?" }
];
